#
# GNUmakefile for target NSPopover_test
# begin - generated by buildtool
#

include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = NSPopover_test

NSPopover_test_OBJC_FILES = NSPopover_test/PopoverViewController.m \
	NSPopover_test/main.m \
	NSPopover_test/AppDelegate.m 

NSPopover_test_C_FILES = 

NSPopover_test_CPP_FILES = 

NSPopover_test_OBJCPP_FILES = 

NSPopover_test_RESOURCE_FILES = NSPopover_test/Assets.xcassets \
	NSPopover_test/Base.lproj/MainMenu.xib \
	NSPopover_test/PopoverViewController.xib \
	NSPopover_testInfo.plist 

ADDITIONAL_INCLUDE_DIRS += -I. \
	-I./NSPopover_test 

ADDITIONAL_OBJC_LIBS += 

include $(GNUSTEP_MAKEFILES)/common.make
include $(GNUSTEP_MAKEFILES)/application.make

#
# end - generated makefile
#
